name: Update localization

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  synchronize-with-crowdin:
    if: github.repository_owner == 'goatcorp'
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Update localization
      uses: crowdin/github-action@1.4.8
      with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          
          # We should put this to true when every language has someone that can approve
          export_only_approved: false
          
          push_translations: true
          commit_message: 'Update localization'
          create_pull_request: true
          pull_request_title: 'Update localization'
          pull_request_body: 'Update localization with latest translations from crowdin'
          config: '.github/crowdin.yml'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        CROWDIN_PROJECT_ID: ${{secrets.CROWDIN_PROJECT_ID}}
        CROWDIN_PERSONAL_TOKEN: ${{secrets.CROWDIN_PERSONAL_TOKEN}}
